# Generated by Django 2.2.4 on 2020-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventKeyWord',
            fields=[
                ('k_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('e_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'EventKeyWord',
            },
        ),
        migrations.CreateModel(
            name='EventParameter',
            fields=[
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_value', models.CharField(blank=True, max_length=50, null=True)),
                ('e_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'EventParameter',
            },
        ),
        migrations.CreateModel(
            name='GlobalParameter',
            fields=[
                ('p_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('p_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'GlobalParameter',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('s_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prototype', models.CharField(blank=True, max_length=50, null=True)),
                ('transform', models.CharField(blank=True, max_length=50, null=True)),
                ('e_id', models.CharField(blank=True, max_length=50, null=True)),
                ('perspective_bias', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SensitiveWord',
            },
        ),
    ]
