# Generated by Django 2.2.4 on 2020-02-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systemmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalparameter',
            name='p_instruction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
