# Generated by Django 2.2.4 on 2019-08-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Test',
        ),
    ]
