# Generated by Django 2.2.4 on 2020-01-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
