# Generated by Django 2.2.4 on 2019-12-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('ua_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=30, null=True)),
                ('statusnum', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('geo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UserActivity',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('ub_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=30, null=True)),
                ('originalnum', models.IntegerField(blank=True, null=True)),
                ('commentnum', models.IntegerField(blank=True, null=True)),
                ('retweetnum', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserBehavior',
            },
        ),
    ]
