# Generated by Django 2.2.4 on 2019-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0002_auto_20190831_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('keywords_dict', models.CharField(max_length=50)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('content', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.NullBooleanField()),
                ('follow_num', models.IntegerField()),
                ('fans_num', models.IntegerField()),
                ('tweets_num', models.IntegerField()),
                ('authentication', models.CharField(default='0', max_length=50)),
                ('address', models.CharField(default='0', max_length=50)),
                ('event', models.ManyToManyField(to='Mainevent.Event')),
            ],
            options={
                'db_table': 'Figure',
            },
        ),
        migrations.CreateModel(
            name='Hot_post',
            fields=[
                ('h_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('forward', models.IntegerField()),
                ('like', models.IntegerField()),
                ('content', models.TextField()),
                ('keywords_dict', models.CharField(max_length=50)),
                ('timestamp', models.TimeField()),
                ('ip', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('store_time', models.TimeField()),
            ],
            options={
                'db_table': 'Hot_post',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('forward', models.IntegerField()),
                ('like', models.IntegerField()),
                ('content', models.TextField()),
                ('keywords_dict', models.CharField(max_length=50)),
                ('timestamp', models.TimeField()),
                ('ip', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('event', models.ManyToManyField(to='Mainevent.Event')),
            ],
            options={
                'db_table': 'Information',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
