# Generated by Django 2.2.4 on 2019-12-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0002_useractivity_userbehavior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hot_post',
            old_name='ip',
            new_name='send_ip',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='ip',
            new_name='send_ip',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ip',
            new_name='send_ip',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='ip',
            new_name='send_ip',
        ),
    ]
