# Generated by Django 2.2.4 on 2019-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0003_auto_20190901_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='event',
        ),
        migrations.DeleteModel(
            name='Hot_post',
        ),
        migrations.RemoveField(
            model_name='information',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Figure',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
