# Generated by Django 2.2.4 on 2020-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0003_auto_20200206_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_analyze',
            name='into_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
