# Generated by Django 2.2.4 on 2020-02-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0004_event_analyze_into_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hot_post',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='status',
            new_name='monitor_status',
        ),
        migrations.RemoveField(
            model_name='information',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='information',
            name='date',
        ),
        migrations.RemoveField(
            model_name='information',
            name='i_level',
        ),
        migrations.RemoveField(
            model_name='information',
            name='keywords_dict',
        ),
        migrations.RemoveField(
            model_name='information',
            name='retweeted',
        ),
        migrations.AddField(
            model_name='information',
            name='cal_status',
            field=models.IntegerField(default=0),
        ),
    ]
