# Generated by Django 2.2.4 on 2019-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0005_event_figure_hot_post_information_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='e_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
