# Generated by Django 2.2.4 on 2019-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0005_auto_20191204_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='hazard_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='store_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='store_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
