# Generated by Django 2.2.4 on 2020-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0006_event_semantic'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='add_manully',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
