# Generated by Django 2.2.4 on 2019-12-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0006_auto_20191206_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserBehavior',
        ),
    ]
