# Generated by Django 2.2.4 on 2020-02-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0007_information_add_manully'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='if_manul',
            new_name='cal_status',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='monitor_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='begin_timestamp',
        ),
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='event',
            name='uid',
        ),
        migrations.AddField(
            model_name='figure',
            name='identitystatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='computestatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='figure',
            name='monitorstatus',
            field=models.IntegerField(default=1),
        ),
    ]
