# Generated by Django 2.2.4 on 2019-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0007_auto_20190904_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='event',
        ),
        migrations.RemoveField(
            model_name='information',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='figure',
            field=models.ManyToManyField(to='Mainevent.Figure'),
        ),
        migrations.AddField(
            model_name='event',
            name='information',
            field=models.ManyToManyField(to='Mainevent.Information'),
        ),
    ]
