# Generated by Django 2.2.4 on 2020-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0007_information_add_manully'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_analyze',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_analyze',
            name='weibo_count',
            field=models.IntegerField(default=0),
        ),
    ]
