# Generated by Django 2.2.4 on 2019-09-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0008_auto_20190905_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
