# Generated by Django 2.2.4 on 2020-02-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0008_auto_20200217_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='es_index_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
