# Generated by Django 2.2.4 on 2020-02-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0008_auto_20200217_1701'),
        ('Mainevent', '0009_auto_20200217_1348'),
    ]

    operations = [
    ]
