# Generated by Django 2.2.4 on 2019-09-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0009_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot_post',
            name='similar_event',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
