# Generated by Django 2.2.4 on 2019-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0010_hot_post_similar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='if_manul',
            field=models.IntegerField(default=0),
        ),
    ]
