# Generated by Django 2.2.4 on 2020-02-22 11:17

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0010_merge_20200219_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Hashtag_Senwords',
            fields=[
                ('ehs_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('e_id', models.CharField(blank=True, max_length=30, null=True)),
                ('hashtag', django_mysql.models.JSONField(default=dict)),
                ('global_senword', django_mysql.models.JSONField(default=dict)),
                ('event_senword', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('into_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Event_Hashtag_Senwords',
            },
        ),
        migrations.AddField(
            model_name='event_analyze',
            name='geo_inland',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event_analyze',
            name='geo_outland',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
