# Generated by Django 2.2.4 on 2020-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0011_auto_20200222_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_hashtag_senwords',
            name='e_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event_hashtag_senwords',
            name='ehs_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
