# Generated by Django 2.2.4 on 2019-12-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0011_event_if_manul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='fans_num',
            new_name='fansnum',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='follow_num',
            new_name='friendsnum',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='gender',
            new_name='isreal',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='tweets_num',
            new_name='statusnum',
        ),
        migrations.AddField(
            model_name='figure',
            name='create_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='domian',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='political',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='sex',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='figure',
            name='uid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='user_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='user_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
