# Generated by Django 2.2.4 on 2019-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0012_auto_20191202_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
