# Generated by Django 2.2.4 on 2020-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0013_event_hashtag_senwords_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_semantic',
            name='e_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event_semantic',
            name='es_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
