# Generated by Django 2.2.4 on 2020-02-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0014_auto_20200227_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_analyze',
            name='hot_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_analyze',
            name='negative_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_analyze',
            name='sensitive_index',
            field=models.IntegerField(default=0),
        ),
    ]
