# Generated by Django 2.2.4 on 2020-03-05 09:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0015_auto_20200229_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalysisShow',
            fields=[
                ('e_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geo', django_mysql.models.JSONField(default=dict)),
                ('funs_num', django_mysql.models.JSONField(default=dict)),
                ('friends_num', django_mysql.models.JSONField(default=dict)),
                ('create_time', django_mysql.models.JSONField(default=dict)),
                ('age', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'EventAnalysisShow',
            },
        ),
        migrations.RenameField(
            model_name='event_analyze',
            old_name='geo_inland',
            new_name='geo_info_inland',
        ),
        migrations.RenameField(
            model_name='event_analyze',
            old_name='geo_outland',
            new_name='geo_info_outland',
        ),
        migrations.AddField(
            model_name='event_analyze',
            name='geo_weibo_inland',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event_analyze',
            name='geo_weibo_outland',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
