# Generated by Django 2.2.4 on 2020-04-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0016_auto_20200305_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
