# Generated by Django 2.2.4 on 2020-04-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0017_information_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count_max',
            field=models.IntegerField(default=100000),
        ),
    ]
