# Generated by Django 2.2.4 on 2020-04-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0019_auto_20200410_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='figure_count',
        ),
        migrations.AddField(
            model_name='figure',
            name='info_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
