# Generated by Django 2.2.4 on 2020-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0020_auto_20200410_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden_status',
            field=models.IntegerField(default=0),
        ),
    ]
