# Generated by Django 2.2.4 on 2020-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainevent', '0021_event_hidden_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sensitive_figure_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sensitive_info_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
