# Generated by Django 2.2.5 on 2020-01-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
