# Generated by Django 2.2.5 on 2020-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informationspread',
            fields=[
                ('is_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('mid', models.CharField(blank=True, max_length=30, null=True)),
                ('root_mid', models.CharField(blank=True, max_length=30, null=True)),
                ('spread_count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('hazard_index', models.FloatField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Informationspread',
            },
        ),
    ]
