# Generated by Django 2.2.4 on 2020-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informationspread', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationspread',
            old_name='spread_count',
            new_name='comment_count',
        ),
        migrations.RemoveField(
            model_name='informationspread',
            name='root_mid',
        ),
        migrations.AddField(
            model_name='informationspread',
            name='retweet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
