# Generated by Django 2.2.4 on 2020-02-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informationspread', '0002_auto_20200213_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationspread',
            name='message_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
