# Generated by Django 2.2.4 on 2020-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informationspread', '0004_informationspread_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationspread',
            name='predict',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
