# Generated by Django 2.2.4 on 2020-04-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informationspread', '0005_auto_20200408_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationspread',
            name='mid',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
