# Generated by Django 2.2.4 on 2019-12-16 11:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomain',
            fields=[
                ('ud_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('domains', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserDomain',
            },
        ),
        migrations.CreateModel(
            name='UserKeyWord',
            fields=[
                ('ukw_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('keywords', django_mysql.models.JSONField(default=dict)),
                ('hastags', django_mysql.models.JSONField(default=dict)),
                ('sensitive_words', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserKeyWord',
            },
        ),
        migrations.CreateModel(
            name='UserSocialContact',
            fields=[
                ('uc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=30)),
                ('target_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=30)),
                ('source_name', models.CharField(max_length=50)),
                ('message_type', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserSocialContact',
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('ut_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('topics', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserTopic',
            },
        ),
    ]
