# Generated by Django 2.2.5 on 2020-01-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='sensitivenum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='sensitivenum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
