# Generated by Django 2.2.4 on 2019-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_userdomain_userkeyword_usersocialcontact_usertopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialcontact',
            name='uid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
