# Generated by Django 2.2.5 on 2020-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_auto_20200114_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('uwc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WordCount',
            },
        ),
    ]
