# Generated by Django 2.2.5 on 2020-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_wordcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCount',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='send_ip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
