# Generated by Django 2.2.4 on 2019-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_usersocialcontact_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('mid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('comment', models.IntegerField()),
                ('retweeted', models.IntegerField()),
                ('original_retweeted_time_num', models.IntegerField()),
                ('original_comment_time_num', models.IntegerField()),
                ('original_retweeted_average_num', models.IntegerField()),
                ('original_comment_average_num', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Influence',
            },
        ),
    ]
