# Generated by Django 2.2.4 on 2020-01-16 02:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_influence'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('uwc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('wordcount', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WordCount',
            },
        ),
    ]
