# Generated by Django 2.2.4 on 2020-01-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_influence'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSentiment',
            fields=[
                ('us_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('negtive', models.IntegerField(blank=True, null=True)),
                ('nuetral', models.IntegerField(blank=True, null=True)),
                ('positive', models.IntegerField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserSentiment',
            },
        ),
    ]
