# Generated by Django 2.2.4 on 2020-01-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0005_usersentiment'),
        ('Userprofile', '0005_wordcount'),
    ]

    operations = [
    ]
