# Generated by Django 2.2.4 on 2020-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0007_userinfluence'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserInfluence',
            fields=[
                ('uid_ts', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=30)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('influence', models.IntegerField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('activity', models.IntegerField(blank=True, null=True)),
                ('sensitity', models.IntegerField(blank=True, null=True)),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NewUserInfluence',
            },
        ),
    ]
