# Generated by Django 2.2.4 on 2020-02-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_auto_20200115_1757'),
        ('Userprofile', '0008_newuserinfluence'),
    ]

    operations = [
    ]
