# Generated by Django 2.2.4 on 2020-02-05 08:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0009_merge_20200205_0758'),
    ]

    operations = [
        
    ]
