# Generated by Django 2.2.4 on 2020-02-11 03:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0010_auto_20200205_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('uwc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('wordcount', django_mysql.models.JSONField(default=dict)),
                ('timestamp', models.BigIntegerField()),
                ('store_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WordCount',
            },
        ),
        migrations.AddField(
            model_name='userdomain',
            name='main_domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
