# Generated by Django 2.2.4 on 2020-02-17 11:28

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0011_auto_20200211_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='source',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='target',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='target_name',
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='comment_source',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='comment_target',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='retweet_source',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='retweet_target',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
