# Generated by Django 2.2.4 on 2020-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0012_auto_20200217_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='comment_source',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='comment_target',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='retweet_source',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='retweet_target',
        ),
        migrations.RemoveField(
            model_name='usersocialcontact',
            name='uid',
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='message_type',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='source_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='target',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialcontact',
            name='target_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersocialcontact',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersocialcontact',
            name='uc_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
