# Generated by Django 2.2.4 on 2020-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0013_auto_20200219_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='ua_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
