# Generated by Django 2.2.4 on 2020-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0015_auto_20200417_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserinfluence',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
