# Generated by Django 2.2.4 on 2020-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0017_auto_20200420_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
