# Generated by Django 2.2.4 on 2020-04-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0018_auto_20200420_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
