# Generated by Django 2.2.4 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textextend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendReview',
            fields=[
                ('ie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('root_uid', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('root_mid', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=400, null=True)),
                ('timestamp', models.BigIntegerField(null=True)),
                ('send_ip', models.CharField(max_length=20, null=True)),
                ('geo', models.CharField(max_length=50, null=True)),
                ('message_type', models.IntegerField(null=True)),
                ('source', models.CharField(max_length=20, null=True)),
                ('process_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ExtendReview',
            },
        ),
        migrations.CreateModel(
            name='ExtendTask',
            fields=[
                ('e_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cal_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ExtendTask',
            },
        ),
    ]
